<a href="https://colab.research.google.com/github/2303A51680/b23_1680/blob/main/LAB_03(class_work).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
fp=open('sample.txt','w')
fp.write("hello\n")
fp.write("hai\n")
fp.write("this is file handling in python\n")
fp.write("sr university\n")
fp.write("Rishitha\n")
fp.close()
fp=open('sample.txt','r')
for line in fp:
    print(line)
fp.close()

hello

hai

this is file handling in python

sr university

Rishitha



In [53]:
fp=open('sample.txt','r')
info=fp.read()
print(info)


hello
hai
this is file handling in python
sr university
Rishitha
appending new data...
appending new data...



In [55]:
file=open("sample.txt","r")
line1=fp.readline()
line2=fp.readline()
print("first line:",line)
print("second line:",line2)




first line: ['hello\n', 'hai\n', 'this is file handling in python\n', 'sr university\n', 'Rishitha\n']
second line: 


In [65]:
fp=open("sample.txt","r")
lines=fp.readlines()
print("all lines as list:",lines)
fp.close()

all lines as list: ['hello\n', 'hai\n', 'this is file handling in python\n', 'sr university\n', 'Rishitha\n', 'appending new data...\n', 'appending new data...\n', 'appending new data...\n']


In [68]:
fp=open("sample.txt","a")
fp.write("appending new data...\n")
fp.close()
fp=open("sample.txt","r")
print(fp.read())
fp.close()

hello
hai
this is file handling in python
sr university
Rishitha
appending new data...
appending new data...
appending new data...
appending new data...
appending new data...
appending new data...



In [70]:
import csv
with open("data.csv","w",newline="")as fp:
  wr=csv.writer(fp)
  wr.writerows([["Name","Age","Course"],["jaya",21,"CSE"],["vaibha",20,"ECE"]])
  from csv import reader
  with open("data.csv","r")as fp:
    rd=csv.reader(fp)
    for row in rd:
      print(row)

In [56]:
import numpy as np

1D Array

In [57]:
arr1=np.array([1,2,3,4])
print("1D Array:",arr1)

1D Array: [1 2 3 4]


2D Array

In [58]:
arr2=np.array([[1,2,3],[4,5,6]])
print("2D Array:\n",arr2)

2D Array:
 [[1 2 3]
 [4 5 6]]


Zeros Array

In [59]:
zeros_arr=np.zeros((3,3))
print("Zeros Array:\n",zeros_arr)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Ones Array

In [60]:
ones_arr=np.ones((2,4))
print("Ones Array:\n",ones_arr)

Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Range of numbers

In [61]:
range_arr=np.arange(0,10,2)
print("Range Array:",range_arr)

Range Array: [0 2 4 6 8]


Random Array

In [62]:
rand_arr=np.random.rand(2,3)
print("Random Array:\n",rand_arr)

Random Array:
 [[0.66601935 0.23981052 0.62353678]
 [0.08416819 0.27642138 0.58136328]]


Array Attribute

In [72]:
arr=np.array([[1,2,3],[4,5,6]])
print("Shape:",arr.shape)           #roes,colums
print("Dimension:",arr.ndim)        #2D array

print("Data Type:",arr.dtype)       #int64 or float64
print("Size:",arr.size)             #Total elements
print("Item Size:",arr.itemsize)    #Bytes per element

Shape: (2, 3)
Dimension: 2
Data Type: int64
Size: 6
Item Size: 8


Array Insexing and Slicing

In [73]:
arr=np.array([10,20,30,40,50])
print("first elements:",arr[0])
print("last element:",arr[-1])
print("slice [1:4]):",arr[1:4])
print("every second element:",arr[::2])

first elements: 10
last element: 50
slice [1:4]): [20 30 40]
every second element: [10 30 50]


2D indexing

In [75]:
arr2=np.array([[1,2,3],[4,5,6]])
print("element at row 1, col 2:",arr2[0,1])
print("second roe:",arr2[1,:])
print("second column:",arr2[:,1])

element at row 1, col 2: 2
second roe: [4 5 6]
second column: [2 5]


Array Operations
Arthmetic Operations

In [76]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Addition:",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("Power:",a**2)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Power: [1 4 9]


Mathematical Functions

In [78]:
arr=np.array([0,np.pi/2,np.pi])
print("sine:",np.sin(arr))
print("cosine:",np.cos(arr))
print("square root:",np.sqrt([1,4,9]))
print("exponential:",np.exp([1,2]))
print("logorithm:",np.log([1,np.e,np.e**2]))

sine: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cosine: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
square root: [1. 2. 3.]
exponential: [2.71828183 7.3890561 ]
logorithm: [0. 1. 2.]


Aggregate Functions

In [79]:

arr=np.array([[1,2,3],[4,5,6]])
print("sum:",np.sum(arr))
print("min:",np.min(arr))
print("max:",np.max(arr))
print("mean:",np.mean(arr))
print("median:",np.median(arr))
print("standard deviation:",np.std(arr))
print("sum of axis 0:",np.sum(arr,axis=0))
print("sum of axis 1:",np.sum(arr,axis=1))

sum: 21
min: 1
max: 6
mean: 3.5
median: 3.5
standard deviation: 1.707825127659933
sum of axis 0: [5 7 9]
sum of axis 1: [ 6 15]


Broadcasting

In [80]:
a=np.array([1,2,3])
b=5
print("add scalar to array:",a+b)
c=np.array([[1],[2],[3]])
d=np.array([4,5,6])
print("broadcasted sum:\n",c+d)

add scalar to array: [6 7 8]
broadcasted sum:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


Matrix Operations

In [82]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print("Mtarix Multiplication:\n",np.dot(A,B))
print("Transpose:\n",A.T)
print("Inverse:\n",np.linalg.inv(A))
print("Determinant:",np.linalg.det(A))

Mtarix Multiplication:
 [[19 22]
 [43 50]]
Transpose:
 [[1 3]
 [2 4]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant: -2.0000000000000004


In [85]:
import numpy as np

marks = np.array([
[85, 90, 88],
[78, 81, 85],
[92, 89, 95]
])
print("Average marks per student:", np.mean(marks, axis=1))
print("Average marks per subject:", np.mean(marks, axis=0))
print("Highest marks in each subject:", np.max(marks, axis=0))
print("Lowest marks in each subject:", np.min(marks, axis=0))

Average marks per student: [87.66666667 81.33333333 92.        ]
Average marks per subject: [85.         86.66666667 89.33333333]
Highest marks in each subject: [92 90 95]
Lowest marks in each subject: [78 81 85]
