<a href="https://colab.research.google.com/github/2303A51680/b23_1680/blob/main/LAB_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [86]:
import numpy as np


In [87]:
np.random.seed(42)  # For reproducibility
scores = np.random.randint(0, 101, size=(4, 4))
print("Generated 4x4 Test Scores:\n", scores)

Generated 4x4 Test Scores:
 [[51 92 14 71]
 [60 20 82 86]
 [74 74 87 99]
 [23  2 21 52]]


In [88]:
row_means = np.mean(scores, axis=1)
col_means = np.mean(scores, axis=0)
print("\nRow-wise Means:", row_means)
print("Column-wise Means:", col_means)


Row-wise Means: [57.  62.  83.5 24.5]
Column-wise Means: [52. 47. 51. 77.]


In [89]:
std_dev = np.std(scores)
variance = np.var(scores)
print("\nStandard Deviation (Global):", std_dev)
print("Variance (Global):", variance)



Standard Deviation (Global): 30.509219917919893
Variance (Global): 930.8125


In [90]:
global_max = np.max(scores)
global_min = np.min(scores)
max_index = np.unravel_index(np.argmax(scores), scores.shape)
min_index = np.unravel_index(np.argmin(scores), scores.shape)
print("\nGlobal Max:", global_max, "at index", max_index)
print("Global Min:", global_min, "at index", min_index)


Global Max: 99 at index (np.int64(2), np.int64(3))
Global Min: 2 at index (np.int64(3), np.int64(1))


In [91]:
import numpy as np

In [93]:
np.random.seed(42)  # For reproducibility
image = np.random.randint(0, 256, size=(3, 3, 3), dtype=np.uint8)
print("Original RGB Image Array:\n", image)

Original RGB Image Array:
 [[[102 220 225]
  [ 95 179  61]
  [234 203  92]]

 [[  3  98 243]
  [ 14 149 245]
  [ 46 106 244]]

 [[ 99 187  71]
  [212 153 199]
  [188 174  65]]]


In [95]:
red_channel = image[:, :, 0]
green_channel = image[:, :, 1]
blue_channel = image[:, :, 2]
print("\nRed Channel:\n", red_channel)
print("\nGreen Channel:\n", green_channel)
print("\nBlue Channel:\n", blue_channel)




Red Channel:
 [[102  95 234]
 [  3  14  46]
 [ 99 212 188]]

Green Channel:
 [[220 179 203]
 [ 98 149 106]
 [187 153 174]]

Blue Channel:
 [[225  61  92]
 [243 245 244]
 [ 71 199  65]]


In [96]:
avg_red = np.mean(red_channel)
avg_green = np.mean(green_channel)
avg_blue = np.mean(blue_channel)

print("\nAverage Intensity - Red:", avg_red)
print("Average Intensity - Green:", avg_green)
print("Average Intensity - Blue:", avg_blue)


Average Intensity - Red: 110.33333333333333
Average Intensity - Green: 163.22222222222223
Average Intensity - Blue: 160.55555555555554


In [97]:
brightened_image = np.clip(image + 50, 0, 255).astype(np.uint8)
print("\nBrightened Image Array:\n", brightened_image)


Brightened Image Array:
 [[[152  14  19]
  [145 229 111]
  [ 28 253 142]]

 [[ 53 148  37]
  [ 64 199  39]
  [ 96 156  38]]

 [[149 237 121]
  [  6 203 249]
  [238 224 115]]]
